apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apps-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: devsearch.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devsearch-service
            port:
              number: 80
  - host: portfolio.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-service
            port:
              number: 80
  - host: techweb.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: techweb-service
            port:
              number: 80
  - host: gym.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gym-service
            port:
              number: 80
  - host: myblog.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myblog-service
            port:
              number: 80
  - host: studybud.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: studybud-service
            port:
              number: 80