apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx  # Adjust this if you have a custom class
  rules:
    - host: 48.216.151.143.nip.io
      http:
        paths:
          - path: /()(.*)
            pathType: Prefix
            backend:
              service:
                name: landing-page
                port:
                  number: 80
          - path: /devsearch(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: devsearch
                port:
                  number: 8004
          - path: /techweb(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: gym
                port:
                  number: 8002
          - path: /portfolio(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: portfolio
                port:
                  number: 8000
          - path: /socialapp(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: socialapp
                port:
                  number: 8001
          - path: /blog(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: blog
                port:
                  number: 8003
