apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apps-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: 48.216.151.143.nip.io
      http:
        paths:
          - path: /devsearch/static(/.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: devsearch-service
                port:
                  number: 80
          - path: /devsearch(/.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: devsearch-service
                port:
                  number: 80
          - path: /techweb/static(/.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: techweb-service
                port:
                  number: 80
          - path: /techweb(/.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: techweb-service
                port:
                  number: 80
          - path: /studybud/static(/.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: studybud-service
                port:
                  number: 80
          - path: /studybud(/.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: studybud-service
                port:
                  number: 80
          - path: /gym/static(/.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: gym-service
                port:
                  number: 80
          - path: /gym(/.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: gym-service
                port:
                  number: 80
          - path: /myblog/static(/.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: myblog-service
                port:
                  number: 80
          - path: /myblog(/.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: myblog-service
                port:
                  number: 80
          - path: /portfolio/static(/.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: portfolio-service
                port:
                  number: 80
          - path: /portfolio(/.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: portfolio-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devsearch-service # Default service for root path
                port:
                  number: 80