apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apps-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2  # Strip the subpath before forwarding
spec:
  ingressClassName: nginx
  rules:
  - host: 48.216.151.143.nip.io
    http:
      paths:
      # Landing page as default
      - path: /
        pathType: Prefix
        backend:
          service:
            name: landing-page-service
            port:
              number: 80

      # DevSearch App
      - path: /devsearch(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: devsearch-service
            port: 
              number: 80

      # TechWeb App
      - path: /techweb(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: techweb-service
            port:
              number: 80

      # StudyBud App
      - path: /studybud(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: studybud-service
            port:
              number: 80

      # Gym App
      - path: /gym(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: gym-service
            port:
              number: 80

      # MyBlog App
      - path: /myblog(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: myblog-service
            port:
              number: 80