apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apps-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
spec:
  ingressClassName: nginx
  rules:
  - host: 48.216.151.143.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: landing-page-service
            port:
              number: 80

      # Static files for devsearch
      - path: /devsearch/static(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: devsearch-service
            port:
              number: 80
      - path: /devsearch(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: devsearch-service
            port:
              number: 80

      # Static files for techweb
      - path: /techweb/static(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: techweb-service
            port:
              number: 80
      - path: /techweb(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: techweb-service
            port:
              number: 80

      # Static files for studybud
      - path: /studybud/static(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: studybud-service
            port:
              number: 80
      - path: /studybud(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: studybud-service
            port:
              number: 80

      # Static files for gym
      - path: /gym/static(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: gym-service
            port:
              number: 80
      - path: /gym(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: gym-service
            port:
              number: 80

      # Static files for myblog
      - path: /myblog/static(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: myblog-service
            port:
              number: 80
      - path: /myblog(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: myblog-service
            port:
              number: 80
