apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio  # Label required to match Service
    spec:
      containers:
      - name: portfolio
        image: nexusameer/myportfolio:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: portfolio-secret
              key: SECRET_KEY
        - name: DEBUG
          valueFrom:
            secretKeyRef:
              name: portfolio-secret
              key: DEBUG
        - name: EMAIL_HOST
          valueFrom:
            secretKeyRef:
              name: portfolio-secret
              key: EMAIL_HOST
        - name: EMAIL_HOST_USER
          valueFrom:
            secretKeyRef:
              name: portfolio-secret
              key: EMAIL_HOST_USER
        - name: EMAIL_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: portfolio-secret
              key: EMAIL_HOST_PASSWORD
        - name: EMAIL_PORT
          valueFrom:
            secretKeyRef:
              name: portfolio-secret
              key: EMAIL_PORT
        - name: EMAIL_USE_TLS
          valueFrom:
            secretKeyRef:
              name: portfolio-secret
              key: EMAIL_USE_TLS
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: portfolio-secret
              key: DATABASE_URL
